---
language: ruby
sudo: false
cache:
  directories:
    - vendor/bundle
bundler_args: --path vendor/bundle
script:
  - bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  - FACTER_GEM_VERSION="~> 1.6.0"
  - FACTER_GEM_VERSION="~> 1.7.0"
  - FACTER_GEM_VERSION="~> 2.0.0"
  - FACTER_GEM_VERSION="~> 2.1.0"
  - FACTER_GEM_VERSION="~> 2.2.0"
  - FACTER_GEM_VERSION="~> 2.3.0"
matrix:
  fast_finish: true
notifications:
  email: false
